--[[
    FissalRelay_RaffleData.lua
    Auto-generated by Fissal Prime: Golden Ledger Protocol
    Sealed Draw Manifest for Redfur Guilds
    Generated: 2026-10-06T02:06:31.378Z
]]--

FissalRelay = FissalRelay or {}
local FR = FissalRelay

FR.OfficialRaffleLedger = {
    sealed = true,
    weekStart = 1790550000,
    weekLabel = "Sep 27 - Oct 4",
    sealedAt = 1791235392,
    allowedOfficers = {
        all = {

        },
        post = {

        },
        dealers = {

        },
        caravan = {

        }
    },
    voided = {
        users = {

        },
        entries = {

        }
    },
    post = {
        guildKey = "post",
        guildLabel = "Redfur Trading Post",
        weekLabel = "Sep 27 - Oct 4",
        weekStart = 1790550000,
        pot = 1304000,
        tickets = 1304,
        entrants = 41,
        announceMessageId = "1556778801650864162",
        prizes = {
            first = 391200,
            second = 260800,
            third = 130400,
            guild = 521600,
        },
        entrants = {
            ["thecompoundeye"] = { tickets = 200, gold = 200000, entries = 1 },
            ["taskibeowolf"] = { tickets = 150, gold = 150000, entries = 1 },
            ["mahoniart66"] = { tickets = 100, gold = 100000, entries = 1 },
            ["slow-kiki"] = { tickets = 100, gold = 100000, entries = 1 },
            ["hhems"] = { tickets = 60, gold = 60000, entries = 1 },
            ["doganis69"] = { tickets = 55, gold = 55000, entries = 1 },
            ["casadetorre"] = { tickets = 50, gold = 50000, entries = 1 },
            ["fatal_destiny42"] = { tickets = 50, gold = 50000, entries = 1 },
            ["kmkzkitty"] = { tickets = 50, gold = 50000, entries = 1 },
            ["scutofwump"] = { tickets = 50, gold = 50000, entries = 1 },
            ["webray"] = { tickets = 50, gold = 50000, entries = 1 },
            ["jakes_golf"] = { tickets = 40, gold = 40000, entries = 1 },
            ["dragonmorning3228"] = { tickets = 30, gold = 30000, entries = 1 },
            ["matthiasthehun76"] = { tickets = 30, gold = 30000, entries = 1 },
            ["protoplasmatic"] = { tickets = 30, gold = 30000, entries = 1 },
            ["alaric_49"] = { tickets = 20, gold = 20000, entries = 1 },
            ["deathstar9000"] = { tickets = 20, gold = 20000, entries = 1 },
            ["homestead5"] = { tickets = 20, gold = 20000, entries = 1 },
            ["kannafoot"] = { tickets = 20, gold = 20000, entries = 1 },
            ["utishta"] = { tickets = 20, gold = 20000, entries = 1 },
            ["valoaven"] = { tickets = 20, gold = 20000, entries = 1 },
            ["zephriandevil"] = { tickets = 15, gold = 15000, entries = 1 },
            ["albai06"] = { tickets = 10, gold = 10000, entries = 1 },
            ["arrassa"] = { tickets = 10, gold = 10000, entries = 1 },
            ["badrock66"] = { tickets = 10, gold = 10000, entries = 1 },
            ["lightminder"] = { tickets = 10, gold = 10000, entries = 1 },
            ["saxon21"] = { tickets = 10, gold = 10000, entries = 1 },
            ["siankan"] = { tickets = 10, gold = 10000, entries = 1 },
            ["theogpettypossum"] = { tickets = 10, gold = 10000, entries = 1 },
            ["zach.phoenix"] = { tickets = 10, gold = 10000, entries = 1 },
            ["kenjay57"] = { tickets = 9, gold = 9000, entries = 1 },
            ["justjim007"] = { tickets = 5, gold = 5000, entries = 1 },
            ["obsidianonyx"] = { tickets = 5, gold = 5000, entries = 1 },
            ["uscss.nostromo"] = { tickets = 5, gold = 5000, entries = 1 },
            ["workoutca"] = { tickets = 5, gold = 5000, entries = 1 },
            ["greenspeaker"] = { tickets = 4, gold = 4000, entries = 1 },
            ["clearlycreation"] = { tickets = 3, gold = 3000, entries = 1 },
            ["jadelyoness"] = { tickets = 3, gold = 3000, entries = 1 },
            ["zantarif"] = { tickets = 3, gold = 3000, entries = 1 },
            ["bravelildragon"] = { tickets = 1, gold = 1000, entries = 1 },
            ["kxavier14"] = { tickets = 1, gold = 1000, entries = 1 },
        },
        winners = {
            { place = 1, name = "@siankan", ticket = 1240, prize = 391200, entries = 1, tickets = 10, gold = 10000 },
            { place = 2, name = "@scutofwump", ticket = 865, prize = 260800, entries = 1, tickets = 50, gold = 50000 },
            { place = 3, name = "@slow-kiki", ticket = 522, prize = 130400, entries = 1, tickets = 100, gold = 100000 },
        }
    },
    dealers = {
        guildKey = "dealers",
        guildLabel = "Redfur Dealers",
        weekLabel = "Sep 27 - Oct 4",
        weekStart = 1790550000,
        pot = 2595000,
        tickets = 2595,
        entrants = 24,
        announceMessageId = "1556778801650864162",
        prizes = {
            first = 648750,
            second = 389250,
            third = 259500,
            guild = 1038000,
        },
        entrants = {
            ["mysyic"] = { tickets = 1000, gold = 1000000, entries = 1 },
            ["isthisappropriate"] = { tickets = 500, gold = 500000, entries = 1 },
            ["zonaz28"] = { tickets = 250, gold = 250000, entries = 1 },
            ["mahoniart66"] = { tickets = 100, gold = 100000, entries = 1 },
            ["rj_brown"] = { tickets = 100, gold = 100000, entries = 1 },
            ["rudeazz"] = { tickets = 100, gold = 100000, entries = 1 },
            ["sirvictor"] = { tickets = 100, gold = 100000, entries = 1 },
            ["baggins_10"] = { tickets = 50, gold = 50000, entries = 1 },
            ["ghrothbot"] = { tickets = 50, gold = 50000, entries = 1 },
            ["warshepherd216"] = { tickets = 50, gold = 50000, entries = 1 },
            ["peradine65"] = { tickets = 35, gold = 35000, entries = 1 },
            ["alitaire"] = { tickets = 25, gold = 25000, entries = 1 },
            ["apoffis3"] = { tickets = 25, gold = 25000, entries = 1 },
            ["batgirl32"] = { tickets = 25, gold = 25000, entries = 1 },
            ["ceeellcee1"] = { tickets = 25, gold = 25000, entries = 1 },
            ["fergal-leadbiter"] = { tickets = 25, gold = 25000, entries = 1 },
            ["serenarlais"] = { tickets = 25, gold = 25000, entries = 1 },
            ["trilobite86"] = { tickets = 25, gold = 25000, entries = 1 },
            ["audiomommy"] = { tickets = 20, gold = 20000, entries = 1 },
            ["foxglove.hoyden"] = { tickets = 20, gold = 20000, entries = 1 },
            ["yuunolishh"] = { tickets = 20, gold = 20000, entries = 1 },
            ["byronthebulb111"] = { tickets = 10, gold = 10000, entries = 1 },
            ["tarbuck"] = { tickets = 10, gold = 10000, entries = 1 },
            ["painkeep"] = { tickets = 5, gold = 5000, entries = 1 },
        },
        winners = {
            { place = 1, name = "@alitaire", ticket = 2357, prize = 648750, entries = 1, tickets = 25, gold = 25000 },
            { place = 2, name = "@zonaz28", ticket = 1651, prize = 389250, entries = 1, tickets = 250, gold = 250000 },
            { place = 3, name = "@trilobite86", ticket = 2489, prize = 259500, entries = 1, tickets = 25, gold = 25000 },
        }
    },
    caravan = {
        guildKey = "caravan",
        guildLabel = "Redfur Trading Caravan",
        weekLabel = "Sep 27 - Oct 4",
        weekStart = 1790550000,
        pot = 56000,
        tickets = 56,
        entrants = 7,
        announceMessageId = "",
        prizes = {
            first = 16800,
            second = 11200,
            third = 5600,
            guild = 22400,
        },
        entrants = {
            ["urshilaku82"] = { tickets = 20, gold = 20000, entries = 1 },
            ["solagratia"] = { tickets = 10, gold = 10000, entries = 1 },
            ["toejam60"] = { tickets = 10, gold = 10000, entries = 1 },
            ["crazyhippiechick"] = { tickets = 5, gold = 5000, entries = 1 },
            ["eirri"] = { tickets = 5, gold = 5000, entries = 1 },
            ["skelly_punk"] = { tickets = 5, gold = 5000, entries = 1 },
            ["silverhawk628"] = { tickets = 1, gold = 1000, entries = 1 },
        },
        winners = {

        }
    }
}
