--[[
    FissalRelay_RaffleData.lua
    Auto-generated by Fissal Prime: Golden Ledger Protocol
    Sealed Draw Manifest for Redfur Guilds
    Generated: 2026-10-05T21:23:21.633Z
]]--

FissalRelay = FissalRelay or {}
local FR = FissalRelay

FR.OfficialRaffleLedger = {
    sealed = true,
    weekStart = 1790550000,
    weekLabel = "Sep 27 - Oct 4",
    sealedAt = 1791235392,
    allowedOfficers = {
        all = {

        },
        post = {

        },
        dealers = {

        },
        caravan = {

        }
    },
    voided = {
        users = {

        },
        entries = {

        }
    },
    post = {
        guildKey = "post",
        guildLabel = "Redfur Trading Post",
        weekLabel = "Sep 27 - Oct 4",
        weekStart = 1790550000,
        pot = 1304000,
        tickets = 1304,
        entrants = 41,
        announceMessageId = "1556778801650864162",
        prizes = {
            first = 391200,
            second = 260800,
            third = 130400,
            guild = 521600,
        },
        winners = {
            { place = 1, name = "@siankan", ticket = 1240, prize = 391200, entries = 1, tickets = 10, gold = 10000 },
            { place = 2, name = "@scutofwump", ticket = 865, prize = 260800, entries = 1, tickets = 50, gold = 50000 },
            { place = 3, name = "@slow-kiki", ticket = 522, prize = 130400, entries = 1, tickets = 100, gold = 100000 },
        }
    },
    dealers = {
        guildKey = "dealers",
        guildLabel = "Redfur Dealers",
        weekLabel = "Sep 27 - Oct 4",
        weekStart = 1790550000,
        pot = 2595000,
        tickets = 2595,
        entrants = 24,
        announceMessageId = "1556778801650864162",
        prizes = {
            first = 648750,
            second = 389250,
            third = 259500,
            guild = 1038000,
        },
        winners = {
            { place = 1, name = "@alitaire", ticket = 2357, prize = 648750, entries = 1, tickets = 25, gold = 25000 },
            { place = 2, name = "@zonaz28", ticket = 1651, prize = 389250, entries = 1, tickets = 250, gold = 250000 },
            { place = 3, name = "@trilobite86", ticket = 2489, prize = 259500, entries = 1, tickets = 25, gold = 25000 },
        }
    },
    caravan = {
        guildKey = "caravan",
        guildLabel = "Redfur Trading Caravan",
        weekLabel = "Sep 27 - Oct 4",
        weekStart = 1790550000,
        pot = 56000,
        tickets = 56,
        entrants = 7,
        announceMessageId = "",
        prizes = {
            first = 16800,
            second = 11200,
            third = 5600,
            guild = 22400,
        },
        winners = {

        }
    }
}
