--[[
    FissalRelay_RaffleData.lua
    Auto-generated by Fissal Prime: Golden Ledger Protocol
    Sealed Draw Manifest for Redfur Guilds
    Generated: 2026-09-18T04:21:53.499Z
]]--

FissalRelay = FissalRelay or {}
local FR = FissalRelay

FR.OfficialRaffleLedger = {
    sealed = true,
    weekStart = 1788735600,
    weekLabel = "Sep 6 - Sep 13",
    sealedAt = 1789459996,
    post = {
        guildKey = "post",
        guildLabel = "Redfur Trading Post",
        weekLabel = "Sep 6 - Sep 13",
        weekStart = 1788735600,
        pot = 1996000,
        tickets = 1996,
        entrants = 51,
        announceMessageId = "1549332265559924798",
        prizes = {
            first = 598800,
            second = 399200,
            third = 199600,
            guild = 798400,
        },
        winners = {
            { place = 1, name = "@albai06", ticket = 291, prize = 598800, entries = 2, tickets = 20, gold = 20000 },
            { place = 2, name = "@taskibeowolf", ticket = 1415, prize = 399200, entries = 2, tickets = 300, gold = 300000 },
            { place = 3, name = "@utishta", ticket = 843, prize = 199600, entries = 1, tickets = 20, gold = 20000 },
        }
    },
    dealers = {
        guildKey = "dealers",
        guildLabel = "Redfur Dealers",
        weekLabel = "Sep 6 - Sep 13",
        weekStart = 1788735600,
        pot = 2920000,
        tickets = 2920,
        entrants = 35,
        announceMessageId = "1549332265559924798",
        prizes = {
            first = 876000,
            second = 584000,
            third = 292000,
            guild = 1168000,
        },
        winners = {
            { place = 1, name = "@mysyic", ticket = 2364, prize = 876000, entries = 1, tickets = 1000, gold = 1000000 },
            { place = 2, name = "@warshepherd216", ticket = 15, prize = 584000, entries = 1, tickets = 50, gold = 50000 },
            { place = 3, name = "@rj_brown", ticket = 919, prize = 292000, entries = 1, tickets = 100, gold = 100000 },
        }
    }
}
